export {
  GET_ME_DATA_AND_COMPANIES,
  GET_ME_COMPANIES,
  GET_DASHBOARD_COUNTS,
  GET_TAGSOURCES,
  get_tagSources_variables,
  GET_CANDIDATES_CREATED_AT_BY_DATE,
  get_candidates_created_at_by_date_variables,
  GET_RECENTLY_WORK_ON,
  get_recently_work_on_variables,
  GET_HUB_CANDIDATES,
  get_hub_candidates_variables,
  GET_CANDIDATE_BY_ID,
  get_candidate_by_id_variables,
  GET_ADD_CANDIDATE_DROPDOWNS,
  GET_HUB_JOBS,
  GET_HUB_POOLS,
} from './dashboard-candidates'
